all:
	cc filter1.c -o filter1
	cc filter2.c -o filter2
	cc conveer.c -o conveer
	cc textcount.c -o textcount
	cc client.c -o client
	cc server.c -o server
clean:
	rm filter1 filter2 conveer textcount client server
